travel_manager_task:
  description: >
    Read {conversation_input}.
    Call get_weather ONCE with the inferred destination city.
    After the tool Observation, output EXACTLY one line (no markdown, no bullets):
    Final Answer: <≤20 words covering destination, dates (assumed if missing), brief weather, one transport, one stay, 2–3 experiences. Mark assumptions "(assumed)".>
    Rules: No delegation. No questions. No extra text before/after the single line. Do not call tools more than once.
  expected_output: >
    Exactly one line starting with "Final Answer: ".
  agent: travel_manager
